version: "3.8"

services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ml_data
      MYSQL_USER: flask
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    secrets:
      - db_root_password
      - db_user_password
    # volumes:
      #  - ./:/mysql
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    # Enable volumes for development mode only
    volumes:
      - ./:/twe
    depends_on:
      - db
    environment:
      FLASK_SECRET_KEY_FILE: /run/secrets/web_secret_key
      MYSQL_DATABASE: ml_data
      # Unbuffered output so PRINT statements appear in Docker logs
      PYTHONUNBUFFERED: 1
    secrets:
      - web_secret_key

secrets:
  db_root_password:
    file: ./db_root_password.txt
  db_user_password:
    file: ./db_user_password.txt
  web_secret_key:
    file: ./web_secret_key.txt