version: "3.8"

services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ml_data
      MYSQL_USER: flask
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - dbdata:/var/lib/mysql
      # Set container to your timezone and local time
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "3306:3306"
  web:
    build:
      context: ./
      dockerfile: ./docker/webapp.Dockerfile
      target: development
    ports:
      - "5000:5000"
    volumes:
      - data-volume:/twe/src/bokeh_server/data
      # Enable this volume for development mode only
      - ./:/twe
      # Set container to your timezone and local time
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - db
    environment:
      BOKEH_SECRET_KEY_FILE: /run/secrets/bokeh_secret_key
      BOKEH_SIGN_SESSIONS: "yes"
      FLASK_SECRET_KEY_FILE: /run/secrets/web_secret_key
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ml_data
      MYSQL_USER: flask
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
      # Unbuffered output so PRINT statements appear in Docker logs
      PYTHONUNBUFFERED: 1
    secrets:
      - bokeh_secret_key
      - db_user_password
      - db_root_password
      - web_secret_key
  bokeh:
    build:
      context: ./
      dockerfile: ./docker/bokeh.Dockerfile
      target: development
    ports:
      - "5006:5006"
    volumes:
      - data-volume:/twe/src/bokeh_server/data
      # Enable this volume for development mode only
      - ./:/twe
      # Set container to your timezone and local time
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - web
    environment:
      BOKEH_SECRET_KEY_FILE: /run/secrets/bokeh_secret_key
    secrets:
      - bokeh_secret_key

secrets:
  bokeh_secret_key:
    file: ./docker/secrets/bokeh_secret_key.txt
  db_root_password:
    file: ./docker/secrets/db_root_password.txt
  db_user_password:
    file: ./docker/secrets/db_user_password.txt
  web_secret_key:
    file: ./docker/secrets/web_secret_key.txt

volumes:
  dbdata:
  data-volume: