version: "3.8"

services:
  web:
    build:
      target: development
    volumes:
      # Enable this volume for development mode only
      - ./:/twe

  bokeh:
    build:
      target: development
    volumes:
      # Enable this volume for development mode only
      - ./:/twe